### ISSUE TITLE
[v3] Path resolution issue on Windows + broken build script

### ISSUE THREAD

**Issue by wKovacs64** [remix-pwa/remix-pwa#123] opened 2023-09-23 19:54 UTC
Hi,

I'm attempting to upgrade to v3, but running into some problems. First, it appears there may be a path resolution issue on Windows. When I try to run `remix-pwa build` or `remix-pwa dev`, I get the following error:

```
> remix-pwa build

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:405:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:131:11)
    at defaultLoad (node:internal/modules/esm/load:82:3)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:603:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

Windows 11
Node 18

@remix-pwa/cache: 2.0.5
@remix-pwa/strategy: 2.1.3
@remix-pwa/sw: 2.1.4
@remix-pwa/dev: 2.0.19
@remix-pwa/worker-runtime: 2.0.5
remix-pwa: 3.0.10

P.S. To confirm this was a Windows thing, I attempted to build the worker on macOS and it doesn't error, but it doesn't build the worker either (doesn't show up in `public`). However, `remix-pwa dev` DOES build the worker (`public/entry.worker.js`). Still investigating that one.

Thanks for all your work!

**Comment by ShafSpecs** [comment] 2023-09-23 20:00
Ah! Okay, this helped a ton @wKovacs64. Window users were all reporting an error with regards to file resolution, and for some reason, Node doesn't take that into account when resolving paths. Would handle it here manually then 👍

Regarding the build script, I just noticed it:
```
$ npm run build:worker

> build:worker
> remix-pwa build

Building Service Worker in development mode
```  
This is soo wrong since it's supposed to be production. Would produce a fix ASAP, and get back to you

**Comment by ShafSpecs** [comment] 2023-09-23 20:06
Spotted the issue:
https://github.com/remix-pwa/monorepo/blob/5b8a14f5632724928239eefb657ec4f9452099e7/packages/dev/compiler/compiler.ts#L17

It was reading the `.env` of the project. I am sure that if you changed `"build:worker": "remix-pwa build"` script to `"build:worker": "cross-env NODE_ENV=production remix-pwa build"`, it would build successfully. But I should be handling that under the hood myself, so a PR is in order!

**Comment by wKovacs64** [comment] 2023-09-23 20:23
> It was reading the `.env` of the project. I am sure that if you changed `"build:worker": "remix-pwa build"` script to `"build:worker": "cross-env NODE_ENV=production remix-pwa build"`, it would build successfully. But I should be handling that under the hood myself, so a PR is in order!

That was quick! I was going open a second issue for this but ran out of time to gather more info. 😅 Nice find.

**Comment by ShafSpecs** [comment] 2023-09-23 22:42
https://github.com/remix-pwa/monorepo/pulls

**Comment by wKovacs64** [comment] 2023-09-23 23:59
Were those last two changes just published? Tried again with the following versions, but no change in behavior:

@remix-pwa/dev: 2.0.20
remix-pwa 3.0.11

I get the same path resolution error on Windows. On macOS, building now says "Building Service Worker in production mode" but still no output.

**Comment by PatrykWalach** [comment] 2023-09-24 10:05
My stack trace shows error at [line 22](https://github.com/remix-pwa/monorepo/blob/5b8a14f5632724928239eefb657ec4f9452099e7/packages/dev/compiler/utils/config.ts#L70)

and changing the path to use `resolveUrl` fixes the error

```diff
- const workerConfig = (await import(findConfig(remixRoot, 'remix.config', EXTENSIONS) as string).then(
+ const workerConfig = (await import(resolveUrl(findConfig(remixRoot, 'remix.config', EXTENSIONS) as string)).then(

```

**Comment by ShafSpecs** [comment] 2023-09-24 10:07
> My stack trace shows error at [line 22](https://github.com/remix-pwa/monorepo/blob/5b8a14f5632724928239eefb657ec4f9452099e7/packages/dev/compiler/utils/config.ts#L70)
> 
> and changing the path to use `resolveUrl` fixes the error
> 
> ```diff
> - const workerConfig = (await import(findConfig(remixRoot, 'remix.config', EXTENSIONS) as string).then(
> + const workerConfig = (await import(resolveUrl(findConfig(remixRoot, 'remix.config', EXTENSIONS) as string)).then(
> ```

Releasing patch within the next 5 mins

**Comment by ShafSpecs** [comment] 2023-09-24 10:34
https://github.com/remix-pwa/monorepo/pull/79

**Comment by PatrykWalach** [comment] 2023-09-24 11:49
There's also an error with esbuild which stops dev from working
```
Watching for changes in the service worker file...
remix-pwaappentry.worker.ts (set a namespace if this is not a file path)

    entry-module:@remix-pwa/build/magic:2:36:
      2 │       import * as entryWorker from  'E:\remix-pwa\app\entry.worker.ts?user';

```
After escaping the path, dev fully works
```diff
- import * as entryWorker from  '${config.entryWorkerFile}?user';
+ import * as entryWorker from  '${config.entryWorkerFile.replaceAll("\\","\\\\")}?user';
```
[line](
https://github.com/remix-pwa/monorepo/blob/bc875db5bfac91a3f327cf0c1fc26dbb91e7a077/packages/dev/compiler/plugins/entry-module.ts#L52)

**Comment by ShafSpecs** [comment] 2023-09-24 12:08
> There's also an error with esbuild which stops dev from working
> 
> ```
> Watching for changes in the service worker file...
> remix-pwaappentry.worker.ts (set a namespace if this is not a file path)
> 
>     entry-module:@remix-pwa/build/magic:2:36:
>       2 │       import * as entryWorker from  'E:\remix-pwa\app\entry.worker.ts?user';
> ```
> 
> After escaping the path, dev fully works
> 
> ```diff
> - import * as entryWorker from  '${config.entryWorkerFile}?user';
> + import * as entryWorker from  '${config.entryWorkerFile.replaceAll("\\","\\\\")}?user';
> ```
> 
> [line](https://github.com/remix-pwa/monorepo/blob/bc875db5bfac91a3f327cf0c1fc26dbb91e7a077/packages/dev/compiler/plugins/entry-module.ts#L52)

Is this Windows?

Secondly, was the above issue fixed?

**Comment by wKovacs64** [comment] 2023-09-24 16:53
> Secondly, was the above issue fixed?

The original error I reported seems to be fixed. I now get the same error @PatrykWalach does:

```
Building Service Worker in development mode
💿 Built in: 16.278ms
Watching for changes in the service worker file...
✘ [ERROR] Plugin "sw-side-effects" returned a non-absolute path: C:devwebprojectappentry.worker.ts (set a namespace if this is not a file path)

    entry-module:@remix-pwa/build/magic:2:36:
      2 │       import * as entryWorker from  'C:\dev\web\project\app\entry.worker.ts?user';
```

(Note the backslashes are missing entirely in the non-absolute path.)

I do wonder if there's a higher level fix than manually hunting and replacing backslashes, perhaps some combination of the right functions in [Node's `path` module](https://nodejs.org/api/path.html), like `normalize`, `resolve`, etc. and applying whatever concoction that turns out to be to every place a path is used?

**Comment by ShafSpecs** [comment] 2023-09-24 17:02
> > Secondly, was the above issue fixed?
> 
> The original error I reported seems to be fixed. I now get the same error @PatrykWalach does:
> 
> ```
> Building Service Worker in development mode
> 💿 Built in: 16.278ms
> Watching for changes in the service worker file...
> ✘ [ERROR] Plugin "sw-side-effects" returned a non-absolute path: C:devwebprojectappentry.worker.ts (set a namespace if this is not a file path)
> 
>     entry-module:@remix-pwa/build/magic:2:36:
>       2 │       import * as entryWorker from  'C:\dev\web\project\app\entry.worker.ts?user';
> ```
> 
> (Note the backslashes are missing entirely in the non-absolute path.)
> 
> I do wonder if there's a higher level fix than manually hunting and replacing backslashes, perhaps some combination of the right functions in [Node's `path` module](https://nodejs.org/api/path.html), like `normalize`, `resolve`, etc. and applying whatever concoction that turns out to be to every place a path is used?

Currently, I am not manually hunting and replacing slashes, Windows has an issue with path resolution when it comes to node and therefore, I have to create platform specific sophisticated methods to get them working. For example, the error above, somehow, all slashes got removed (I never use `replace` or `replaceAll` in the path algo), would look out for something I can use

**Comment by ShafSpecs** [comment] 2023-09-24 17:06
https://github.com/remix-pwa/monorepo/blob/8f04020f3e80c63d17a5e4eee074c9a2f4dd58d9/packages/dev/compiler/plugins/side-effects.ts#L11

This is the line it's complaining about, which looks correct to me. Btw, pls are you using `remix-pwa@3.0.12`?

**Comment by wKovacs64** [comment] 2023-09-24 17:12
> Currently, I am not manually hunting and replacing slashes, Windows has an issue with path resolution when it comes to node and therefore, I have to create platform specific sophisticated methods to get them working. For example, the error above, somehow, all slashes got removed (I never use `replace` or `replaceAll` in the path algo), would look out for something I can use

Ah, okay - I was mainly referring to Patryk's fixes.

> Btw, pls are you using `remix-pwa@3.0.12`?

Yep.

**Comment by ShafSpecs** [comment] 2023-09-24 17:14
Would get a util function over there to attempt the fix, but it is mind-boggling I am doing this and not node

**Comment by ShafSpecs** [comment] 2023-09-24 17:27
<img width="776" alt="image" src="https://github.com/remix-pwa/remix-pwa/assets/69679506/4eda2ccb-740c-4097-81b0-0b49ffd7514d">
I've thrown out an issue tracker for this, because to be honest, it is getting a tad-bit frustrating. I can't reproduce the error because this is a node issue (file path resolution is questionable) and I use a Mac. I also hate releasing broken or half-working packages as it doesn't bode well for anybody. But this is beyond something I can actively debug, the best I can do is guess and attempt fixes **in production** (after publishing)

**Comment by ShafSpecs** [comment] 2023-09-24 17:28
Any non-temporary solutions or suggestions are welcome too ❤️

**Comment by ShafSpecs** [comment] 2023-09-25 11:23
Published a new fix (hopefully), available in 3.0.13

**Comment by wKovacs64** [comment] 2023-09-25 13:29
> Published a new fix (hopefully), available in 3.0.13

```
Building Service Worker in development mode
💿 Built in: 15.158ms
Watching for changes in the service worker file...
✘ [ERROR] Do not know how to load path: entry-module:@remix-pwa\build\magic

    node_modules/@remix-pwa/worker-runtime/dist/src/service-worker.internal.js:3:23:
      3 │ import * as build from '@remix-pwa/build/magic';
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by ShafSpecs** [comment] 2023-09-25 14:07
> import * as build from

Released another nightly build for `remix-pwa` - 3.0.14 and for `@remix-pwa/dev` - 2.0.23. `@remix-pwa/worker-runtime` also has been bumped to 2.0.5

**Comment by wKovacs64** [comment] 2023-09-25 14:18
> Released another nightly build for `remix-pwa` - 3.0.14 and for `@remix-pwa/dev` - 2.0.23. `@remix-pwa/worker-runtime` also has been bumped to 2.0.5

Not sure if you intended to release a new version of `@remix-pwa/worker-runtime`, but it's been at 2.0.5 for a few days now on the `dev` dist-tag and that's the version I've had installed.

As for `remix-pwa@3.0.14` and `@remix-pwa/dev@2.0.23`, stuff blew up a bit:

<details>
<pre>
Building Service Worker in development mode
💿 Built in: 14.425ms
Watching for changes in the service worker file...
✘ [ERROR] Plugin "sw-side-effects" returned a non-absolute path: C:devwebmeetup-raffleappentry.worker.ts (set a namespace if this is not a file path)

    entry-module:@remix-pwa/build/magic:2:36:
      2 │       import * as entryWorker from  'C:\dev\web\meetup-raffle\app\entry.worker.ts?user';
        ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Do not know how to load path: assets-module:@remix-sas\dev?assets

    entry-module:@remix-pwa/build/magic:52:27:
      52 │     export { assets } from '@remix-sas/dev?assets';
         ╵                            ~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Cannot read properties of undefined (reading 'id') [plugin sw-routes-modules]

    node_modules/@remix-pwa/dev/node_modules/esbuild/lib/main.js:1435:27:
      1435 │         let result = await callback({
           ╵                            ^

    at onLoad (file:///C:/dev/web/meetup-raffle/node_modules/@remix-pwa/dev/dist/compiler/plugins/routes-module.js:16:77)
    at requestCallbacks.on-load (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:1435:28)
    at handleRequest (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:731:17)
    at handleIncomingPacket (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:756:7)
    at Socket.readFromStdout (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:679:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

  This error came from the "onLoad" callback registered here:

    node_modules/@remix-pwa/dev/node_modules/esbuild/lib/main.js:1293:20:
      1293 │       let promise = setup({
           ╵                     ^

    at setup (file:///C:/dev/web/meetup-raffle/node_modules/@remix-pwa/dev/dist/compiler/plugins/routes-module.js:32:15)
    at handlePlugins (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:1293:21)
    at buildOrContextImpl (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:979:5)
    at Object.buildOrContext (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:787:5)
    at C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:2197:68
    at new Promise (<anonymous>)
    at Object.context (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:2197:27)
    at Object.context (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:2037:58)
    at file:///C:/dev/web/meetup-raffle/node_modules/@remix-pwa/dev/dist/compiler/compiler.js:63:14

  The plugin "sw-routes-modules" was triggered by this import

    entry-module:@remix-pwa/build/magic:5:24:
      5 │ import * as route1 from 'routes/[manifest.webmanifest].ts?worker';
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Cannot read properties of undefined (reading 'id') [plugin sw-routes-modules]

    node_modules/@remix-pwa/dev/node_modules/esbuild/lib/main.js:1435:27:
      1435 │         let result = await callback({
           ╵                            ^

    at onLoad (file:///C:/dev/web/meetup-raffle/node_modules/@remix-pwa/dev/dist/compiler/plugins/routes-module.js:16:77)
    at requestCallbacks.on-load (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:1435:28)
    at handleRequest (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:731:17)
    at handleIncomingPacket (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:756:7)
    at Socket.readFromStdout (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:679:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

  This error came from the "onLoad" callback registered here:

    node_modules/@remix-pwa/dev/node_modules/esbuild/lib/main.js:1293:20:
      1293 │       let promise = setup({
           ╵                     ^

    at setup (file:///C:/dev/web/meetup-raffle/node_modules/@remix-pwa/dev/dist/compiler/plugins/routes-module.js:32:15)
    at handlePlugins (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:1293:21)
    at buildOrContextImpl (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:979:5)
    at Object.buildOrContext (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:787:5)
    at C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:2197:68
    at new Promise (<anonymous>)
    at Object.context (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:2197:27)
    at Object.context (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:2037:58)
    at file:///C:/dev/web/meetup-raffle/node_modules/@remix-pwa/dev/dist/compiler/compiler.js:63:14

  The plugin "sw-routes-modules" was triggered by this import

    entry-module:@remix-pwa/build/magic:6:24:
      6 │ import * as route2 from 'routes/_index.tsx?worker';
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Cannot read properties of undefined (reading 'id') [plugin sw-routes-modules]

    node_modules/@remix-pwa/dev/node_modules/esbuild/lib/main.js:1435:27:
      1435 │         let result = await callback({
           ╵                            ^

    at onLoad (file:///C:/dev/web/meetup-raffle/node_modules/@remix-pwa/dev/dist/compiler/plugins/routes-module.js:16:77)
    at requestCallbacks.on-load (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:1435:28)
    at handleRequest (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:731:17)
    at handleIncomingPacket (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:756:7)
    at Socket.readFromStdout (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:679:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

  This error came from the "onLoad" callback registered here:

    node_modules/@remix-pwa/dev/node_modules/esbuild/lib/main.js:1293:20:
      1293 │       let promise = setup({
           ╵                     ^

    at setup (file:///C:/dev/web/meetup-raffle/node_modules/@remix-pwa/dev/dist/compiler/plugins/routes-module.js:32:15)
    at handlePlugins (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:1293:21)
    at buildOrContextImpl (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:979:5)
    at Object.buildOrContext (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:787:5)
    at C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:2197:68
    at new Promise (<anonymous>)
    at Object.context (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:2197:27)
    at Object.context (C:\dev\web\meetup-raffle\node_modules\@remix-pwa\dev\node_modules\esbuild\lib\main.js:2037:58)
    at file:///C:/dev/web/meetup-raffle/node_modules/@remix-pwa/dev/dist/compiler/compiler.js:63:14

  The plugin "sw-routes-modules" was triggered by this import

    entry-module:@remix-pwa/build/magic:7:24:
      7 │ import * as route3 from 'routes/draw.tsx?worker';
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
</details>

**Comment by ShafSpecs** [comment] 2023-09-25 14:20
Thanks. I give up, I am going to look for a windows pc to test this on in the meantime. Was `entry.worker.js` still getting built tho? If yes, delete it please

**Comment by ShafSpecs** [comment] 2023-09-26 14:50
https://github.com/remix-pwa/monorepo/actions/runs/6314285966/job/17144202056

Already testing for windows exclusively. Hopefully a fix can be out this week

**Comment by ShafSpecs** [comment] 2023-09-26 15:11
Why it fails btw: https://github.com/nodejs/node/issues/31710

**Comment by lfantone** [comment] 2023-09-27 12:41
I created a [PR](https://github.com/remix-pwa/monorepo/pull/92) to solve all the windows related issues in the compiler!
I did run some test in a Windows 11 computer myself and was the service-worker was bundled correctly.

**Comment by wKovacs64** [comment] 2023-09-27 22:43
`remix-pwa dev` seems to work now! 🎉 Still not seeing the worker get output from `remix-pwa build`, though. I assumed they were related, but perhaps that's a separate issue?

```
@remix-pwa/cache@2.0.10
@remix-pwa/strategy@2.1.7
@remix-pwa/sw@2.1.9
@remix-pwa/dev@2.0.27
@remix-pwa/worker-runtime@2.0.6
remix-pwa@3.0.15
```

**Comment by ShafSpecs** [comment] 2023-09-28 06:22
> `remix-pwa dev` seems to work now! 🎉 Still not seeing the worker get output from `remix-pwa build`, though. I assumed they were related, but perhaps that's a separate issue?
> 
> ```
> @remix-pwa/cache@2.0.10
> @remix-pwa/strategy@2.1.7
> @remix-pwa/sw@2.1.9
> @remix-pwa/dev@2.0.27
> @remix-pwa/worker-runtime@2.0.6
> remix-pwa@3.0.15
> ```

Not a separate issue, updated `remix-pwa` to 3.0.16. Might want to test that, everything worked during gh actions run 😕

**Comment by wKovacs64** [comment] 2023-09-28 15:28
> Not a separate issue, updated `remix-pwa` to 3.0.16. Might want to test that, everything worked during gh actions run 😕

Nothin'. Just says `Building Service Worker in production mode` and exits, no `public/entry.worker.js`.

**Comment by wKovacs64** [comment] 2023-09-30 17:02
I just realized `remix-pwa build` is not producing `public/entry.worker.js` on macOS, either. So this particular aspect isn't Windows specific. (I hadn't tried it again since `remix-pwa dev` was fixed on Windows.)

**Comment by ShafSpecs** [comment] 2023-09-30 17:17
> I just realized `remix-pwa build` is not producing `public/entry.worker.js` on macOS, either. So this particular aspect isn't Windows specific. (I hadn't tried it again since `remix-pwa dev` was fixed on Windows.)

Fix coming out soon

**Comment by ShafSpecs** [comment] 2023-09-30 17:33
https://github.com/remix-pwa/monorepo/pull/100

**Comment by ShafSpecs** [comment] 2023-09-30 17:46
<img width="838" alt="image" src="https://github.com/remix-pwa/remix-pwa/assets/69679506/f8960920-eafe-4140-8ced-8a3ca768b8fc">
Soon enough 😄

**Comment by ShafSpecs** [comment] 2023-09-30 17:49
```sh
npm notice === Tarball Details === 
npm notice name:          @remix-pwa/dev                          
npm notice version:       2.0.26-dev.2                            
npm notice filename:      remix-pwa-dev-2.0.26-dev.2.tgz
```
Creating a stable release soon enough, then releasing a new `remix-pwa` version 👍

**Comment by ShafSpecs** [comment] 2023-09-30 18:04
Packages published. Patch bump needed for the fix

**Comment by wKovacs64** [comment] 2023-09-30 18:30
Success, thank you!

**Comment by ShafSpecs** [comment] 2023-09-30 23:36
*Closing this issue as fixed 👍*

**Closed by ShafSpecs** 2023-09-30 23:36 UTC
Labels: bug, help wanted, high priority
